import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */\n" +
  "/* If you want to view the source, please visit the github repository of this plugin */";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/*", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
console.log("Watching for changes...");
